version: '3.8'

services:
  api:
    build: .
    container_name: kmrl_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - .:/app   # live-reload in dev
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: kmrl_postgres
    environment:
      POSTGRES_USER: kmrl
      POSTGRES_PASSWORD: kmrl123
      POSTGRES_DB: kmrl_ingest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kmrl -d kmrl_ingest"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: kmrl_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pgdata:
  miniodata:
